[window]
decorations = "full"
padding = { x = 10, y = 10 }
dynamic_title = true
opacity = 0.92

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
size = 13.0
offset = { x = 0, y = 2 }

[colors.cursor]
text = "#1e1e2e"
cursor = "#cdd6f4"

[colors.selection]
text = "CellForeground"
background = "#44475a"

[selection]
save_to_clipboard = true

[keyboard]
bindings = [
  { key = "C", mods = "Control|Shift", action = "Copy" },
  { key = "V", mods = "Control|Shift", action = "Paste" },
]

